export default {
    FETCH_CONVERSATIONS_START : "FETCH_CONVERSATIONS_START",
    FETCH_CONVERSATIONS_SUCCESS : "FETCH_CONVERSATIONS_SUCCESS",
    FETCH_CONVERSATIONS_ERROR : "FETCH_CONVERSATIONS_ERROR"
}